import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PageLink from "./components/pageLink";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageLink title="About" />
        <PageLink title="Access" />
        <h1>
          Hello,I'm <br />
          Hoppy!
        </h1>
        <PageLink title="Woorks" />
        <PageLink title="hobby" />
      </main>
    </div>
  );
};
export default Home;
