import type { NextPage } from "next";
import {css} from "@emotion/react";
import Head from "next/head";
import Image from "next/image";
import PageLink from "./components/pageLink";

const Home: NextPage = () => {
  return (
    <div css={main}>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div css={links}>
          <PageLink title="About" />
        </div>
        <div css={links}>
          <PageLink title="Access" />
        </div>
        <h1>
          Hello,I'm <br />
          Hoppy!
        </h1>
        <div css={links}>
          <PageLink title="Woorks" />
        </div>
        <div css={links}>
          <PageLink title="hobby" />
        </div>
      </div>
    </div>
  );
};
const main=css`
  width: 100%;
`;
const links=css`
  width: 100%;
`;
export default Home;
